A Dataset with an unequal class distribution

In [21]:
# importing the dependencies
import numpy as np
import pandas as pd

In [22]:
# loading the dataset to pandas dataframe
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [23]:
# first five rows of the date frame
credit_card_data.head(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [24]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [25]:
# distribution of the two classes
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is highly imbalanced dataset

0 --> Legit

1 --> Fraudulent

In [26]:
# separating the legit and fraud transaction
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [27]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

# Under-smapling
Build a sample dataset containing similar distribution of legit and fraudlent transaction

In [28]:
legit_sample = legit.sample(n=492)

In [29]:
print(legit_sample.shape)

(492, 31)

# Concatenate the two dataframe

In [30]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [31]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
76177,56431.0,1.168292,0.198014,0.238912,1.155110,-0.358813,-0.964582,0.231184,-0.210304,0.066097,...,0.044330,0.057587,-0.127265,0.378548,0.654229,-0.330348,0.002516,0.025916,43.68,0
228702,145617.0,-0.848609,0.832208,1.271752,-0.504105,0.102078,0.243730,-0.093980,0.663468,-0.336391,...,-0.001588,-0.126652,-0.022765,0.693745,-0.305866,-0.582818,0.039488,0.058223,2.49,0
63186,50598.0,-0.412961,0.949102,0.763832,1.456914,0.176185,-0.157111,0.186432,0.216058,-0.919552,...,0.154610,0.575780,0.129125,0.239698,-1.443924,-0.557337,-0.053483,-0.107274,5.80,0
160399,113335.0,2.114425,0.046058,-1.871250,0.458446,0.580853,-0.959594,0.564187,-0.453070,0.310327,...,-0.061714,0.056074,-0.030651,-0.586393,0.327538,0.417515,-0.081374,-0.078261,12.99,0
132838,80137.0,1.221247,0.492915,0.047626,1.360042,0.061107,-0.450567,0.098962,-0.122637,0.308370,...,-0.341862,-0.738012,-0.066351,-0.208416,0.623842,-0.497938,0.059375,0.051011,7.72,0

In [32]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [33]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64